#
#  Desktop Settings
#

#spring.devtools.add-properties: false 
#spring.mvc.pathmatch.matching-strategy: ant-path-matcher

logging.config: classpath:log4j2-desktop.yml

#server:
#  port: 8081

#
#
#
#spring.web.resources.static-locations: file:src/main/resources/static/

csap:
  encryption:
    enabled: true
    token: "Will be overwritten by env var"
    algorithm: PBEWITHMD5ANDDES

#  web-server:
#  
#    ssl:
#      # port: xxxx  # defaults to http port + 2, agent is 8013
#      keystore-type: PKCS12
#      keystore-file: classpath:csap-lab.p12
#      keystore-password: "v8IguDAmcJpsqofXt/RhlmjS5YR2agmN" # csap1234
#      key-alias: csap
#      test-domain: csap.org

#  web-server:
#  
#    ssl:
#      client: false     # disable server side ssl client

#      keystore-file: "" # disable embedded ssl server