
#
#  ================ profile: desktop
#

logging.config: classpath:log4j2-desktop.yml

spring:
  
  devtools:
    restart:

#      exclude: "**/*.properties,**/*.css,**/*.html,**/*.json,**/*.js,**/*.yaml,**/*.yml,**/*.png,**/*.gif,**/*.jpg,**/*.svg,**/*.txt,**/*.xml,**/*.ico,**/*.sh,**/*.md,**/*.jmx,**/*.csv,**/*.lua,**/*.py,**/*.cfg"
      additional-exclude: "**/*.jmx,**/*.csv,**/*.json,**/csap-templates/**"

#spring.web.resources:
#  static-locations: file:src/main/resources/static/ #directly serve from src folder instead of target
#  cache:
#    period: 0

csap-core:

  definition-folder: "../../artifacts-support/desktop-definition"
#  definition-folder: "src/main/resources/csap-templates/application-definition/"

  chef-cookbook-path: /Users/peter.nightingale/peters-google-drive/csap/cookbooks
  zing-ps-path: /usr/bin/zing-ps

  custom-properties:
    - 
      name: application-folder
      value: ${applicationFolder:/Users/peter.nightingale/csap}
      
    - 
      name: application-user
      value: ${applicationUser:peter.nightingale}
    - 
      name: demo-property-folder
      value: src/test/resources
  

  events-client-shutdown-attempts: 4

  #
  #  Desktop setup using gradle - use build; for maven use target
  #
  installation-folder: build/csap-platform
  
  # testing only
  ssl-force-hosts:
    - csap-dev20
    
  disable-ssl-validation: false
  
  disable-jmx-collection: true
  
#  host-url-pattern: "https://CSAP_HOST.csap.org:8011"
#  host-url-pattern: "${hostUrlPattern:auto}"

  
  docker:
    enabled: true
    #url: "tcp://ec2-35-86-104-134.us-west-2.compute.amazonaws.com:4243"
    url: "unix:///var/run/docker.sock"

#    url: "unix:///Users/peter.nightingale/docker.sock"
    #    url: "tcp://localhost:4243"
    #url: "tcp://csap-01.csap.org:4243"
#    url: "tcp://ip-10-0-1-103.us-west-2.compute.internal:4243"
    
  kubernetes:
    enabled: false
    config-file: ${user.home}/agent-desktop-kubernetes-folder/config
  
    #
    # testing only
    #
    #test-credential-url: "http://csap-01.csap.org:8011/os/folderZip?path=.kube/config&token=584t76.b0b7c7r75rbc0ml0&service=kubelet"
    test-credential-url: "http://ec2-35-86-104-134.us-west-2.compute.amazonaws.com:8011/os/folderZip?path=.kube/config&token=584t76.b0b7c7r75rbc0ml0&service=kubelet"
#    test-credential-url: "http://ip-10-0-1-103.us-west-2.compute.internal:8011/os/folderZip?path=.kube/config&token=584t76.b0b7c7r75rbc0ml0&service=kubelet"

    #test-credential-url: "http://s-1fpnqp2.some.host.pattern:8011/os/folderZip?path=.kube/config&token=584t76.b0b7c7r75rbc0ml0&service=kubelet"


#    test-credential-url: "http://csap-dev07.csap.org:8011/os/folderZip?path=.kube/config&token=584t76.b0b7c7r75rbc0ml0&service=kubelet-ha"
#    test-credential-url: "http://centos1.csap.org:8011/os/folderZip?path=.kube/config&token=584t76.b0b7c7r75rbc0ml0&service=kubelet" 
  

server:
#  port: 7011
#  port: 8022
  tomcat:
    accesslog:
      enabled: true
      pattern: "%h %l %u %t &quot;%r&quot; %s %b"
      
# log will be pushed to java temp      
  
    
csap:

  security: 
    enabled: true

#    rest-api-filter:
#      token: ${restToken:demoToken}    
      
  performance:
    enabled: true
        
    alert: 
        
      limits:
        
        # agent refreshes are triggered by admin
#        -
#          id: csap.host-status
#          occurences-min: 9
#          collect-time: 1 # allows for migrations
#          collect-units: SECONDS
#          max-time: 7
#          max-units: SECONDS
          
        - 
          id: csap.exception
          ignore-null: true
          occurences-max: 2
          collect-time: 1
          collect-units: MINUTES
  
        # Log Rotations
#        -
#          id: csap.service-jobs.logs
#          occurences-min: 1
#          collect-time: 60
#          collect-units: MINUTES
#          max-time: 30
#          max-units: SECONDS
  

          
        # OS Commands and scripts
#        -
#          id: csap.os-commands
#          collect-time: 2
#          collect-units: MINUTES
#          occurences-max: 200
#          max-time: 5
#          max-units: SECONDS
        - 
          id: csap.service.jobs
          ignore-null: true
          occurences-max: 2
          max-time: 8
          max-units: MINUTES
        - 
          id: csap.os-commands.userScript
          ignore-null: true
          max-time: 10
          max-units: SECONDS
          
        # agent collection thresholds
        - 
          id: csap.collect-http
          collect-time: 1
          collect-units: MINUTES
          occurences-min: 1
          max-time: 3
          max-units: SECONDS
          
#        -
#          id: csap.collect-http.failures
#          ignore-null: true
#          occurences-max: 0
          
          
        - 
          id: csap.collect-jmx
          ignore-null: true
          collect-time: 1
          collect-units: MINUTES
          occurences-min: 1
          max-time: 3
          max-units: SECONDS
          
        - 
          id: csap.collect-jmx.failures
          ignore-null: true
          occurences-max: 0
        - 
          id: csap.collect-jmx.service.failures
          ignore-null: true
          occurences-max: 0
  
        # agent posting data to csaptools analytics service
#        -
#          id: csap.event-publish
#          max-time: 5
#          max-units: SECONDS
          
        - 
          id: csap.event-publish.failures
          occurences-max: 1
          ignore-null: true
#        - 
#          id: csap.event-publish.csap-metrics
#          collect-time: 30
#          collect-units: MINUTES
#          occurences-min: 1
#        - 
#          id: csap.event-publish.csap-reports
#          collect-time: 30
#          collect-units: MINUTES
#          occurences-min: 1
      
        